name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build the books
        run: |
          # Build all packages defined in the flake
          for output in $(nix flake show --json | jq -r '.packages."x86_64-linux" | keys[]'); do 
                nix build .#$output -o "$(echo $output | tr - .)"
          done

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Assets release"
          files: |
            *.pdf
            *.epub
